/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedCommunicationRouteImport } from './routes/_authenticated/communication'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunicationRoute =
  AuthenticatedCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/communication': typeof AuthenticatedCommunicationRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/communication': typeof AuthenticatedCommunicationRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/communication': typeof AuthenticatedCommunicationRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/policies': typeof AuthenticatedPoliciesRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/communication'
    | '/meetings'
    | '/policies'
    | '/tasks'
    | '/api/chat'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/chat'
    | '/communication'
    | '/meetings'
    | '/policies'
    | '/tasks'
    | '/api/chat'
    | '/'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/communication'
    | '/_authenticated/meetings'
    | '/_authenticated/policies'
    | '/_authenticated/tasks'
    | '/api/chat'
    | '/_authenticated/'
    | '/_authenticated/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication': {
      id: '/_authenticated/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedCommunicationRoute: typeof AuthenticatedCommunicationRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedCommunicationRoute: AuthenticatedCommunicationRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
